# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: "/"
    weight: 10
  - name: Research
    url: research
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Publications
    url: publication
    weight: 40
# - name: Leisure
#   url: leisure
#   weight: 45
# - name: photos
#   parent: Leisure
#   url: leisure/photos
#   weight: 46
  - name: Position
    url: position
    weight: 50
  - name: Contact
    url: contact
    weight: 70
